
'use client';

import { useState, useEffect } from 'react';
import { cn } from '../lib/utils';

const truths = [
    "Pernahkah kamu ketahuan menyanyi di kamar mandi dengan suara yang sangat kencang?",
    "Apa kebiasaan paling aneh yang kamu lakukan saat sendirian di rumah?",
    "Jujur, apakah kamu pernah mengupil lalu memakannya?",
    "Apa nama panggilanmu yang paling memalukan dan bagaimana ceritanya kamu bisa mendapatkannya?",
    "Pernahkah kamu salah kirim pesan ke atasan atau dosen yang seharusnya ditujukan untuk teman? Apa isi pesannya?",
    "Apa makanan paling aneh yang kamu suka tapi orang lain mungkin menganggapnya menjijikkan?",
    "Pernahkah kamu kentut keras di depan umum lalu pura-pura tidak tahu?",
    "Jika kamu bisa memiliki kekuatan super yang paling konyol, kekuatan apa yang akan kamu pilih?",
    "Apa film atau lagu yang diam-diam kamu sukai tapi malu untuk mengakuinya di depan orang lain?",
    "Apa kesan pertamamu saat kita bertemu?",
    "Apa yang awalnya membuatmu tertarik padaku?",
    "Apa yang ada di pikiranmu waktu pertama kali kita ketemu?",
    "Menurutmu, apa yang membuat hubungan kita unik dibandingkan pasangan lain?",
    "Apa hal yang paling kamu sukai dari diriku, dan apa kebiasaan atau sikapku yang paling menyebalkan menurutmu?",
    "Kapan terakhir kali aku membuatmu benar-benar marah atau kesal?",
    "Menurutmu, apakah kita memiliki love language yang sama?",
    "Kenapa hubunganmu dengan mantan yang sebelumnya berakhir?",
    "Di masa tua nanti saat kita masih bersama, kegiatan apa yang paling ingin kamu lakukan berdua?",
    "Apa pendapatmu tentang pernikahan dan di usia berapa kamu ingin menikah?",
    "Jika ternyata aku bukan jodohmu, bagaimana tanggapanmu?",
    "Apa ketakutan terbesarmu dalam sebuah hubungan?",
    "Apakah kamu pernah merasa bosan atau jenuh menjalani hubungan denganku?",
    "Adakah sesuatu yang ingin kamu tanyakan kepadaku tetapi kamu takut untuk menanyakannya?",
    "Kalau bisa bertukar hidup dengan salah satu teman di ruangan ini selama sehari, siapa yang akan kamu pilih dan mengapa?",
    "Menurutmu, siapa di antara kita yang paling dramatis kalau sedang bercerita tentang masalahnya?",
    "Pernahkah kamu berpura-pura sibuk atau punya alasan lain agar tidak perlu ikut nongkrong dengan geng ini? Kapan itu terjadi?",
    "Apa sifat burukku sebagai teman yang paling ingin kamu hilangkan?",
    "Siapa di antara kita yang paling bisa diandalkan dalam situasi darurat, dan siapa yang paling chaos?",
    "Hal paling menyebalkan apa yang pernah kamu alami saat nongkrong bareng kita?",
    "Jika kita semua ikut sebuah reality show, siapa yang akan tereliminasi pertama dan siapa yang akan menjadi pemenangnya?",
    "Siapa orang di ruangan ini yang paling tidak kamu sukai, dan apa alasannya?",
    "Apa kebohongan terbesar yang pernah kamu katakan kepada siapa pun?",
    "Pernahkah kamu selingkuh dari pasanganmu?",
    "Apa rahasia terbesar yang kamu sembunyikan dari orang tuamu sampai saat ini?",
    "Apa penyesalan terbesarmu dalam hidup?",
    "Apa kebohongan terakhir yang kamu ucapkan?",
    "Apa hal paling memalukan yang pernah kamu lakukan saat berkencan?",
    "Pernahkah kamu secara tidak sengaja menabrak sesuatu (atau seseorang!) dengan mobilmu?",
    "Sebutkan seseorang yang kamu pura-pura suka padahal sebenarnya tidak tahan.",
    "Apa nama panggilanmu yang paling aneh?",
    "Apa pengalaman fisikmu yang paling menyakitkan?",
    "Jembatan (hubungan) apa yang kamu senang telah kamu bakar?",
    "Apa hal paling gila yang pernah kamu lakukan di transportasi umum?",
    "Jika kamu bertemu jin, apa tiga permintaanmu?",
    "Jika kamu bisa menunjuk siapa pun di bumi untuk menjadi Presiden, siapa orangnya dan mengapa?",
    "Apa hal paling kejam yang pernah kamu katakan kepada orang lain?",
    "Siapa ciuman terburukmu?",
    "Apa satu hal yang akan kamu lakukan jika kamu tahu tidak akan ada konsekuensinya?",
    "Apa hal paling konyol yang pernah kamu lakukan di depan cermin?",
    "Apa hal paling kejam yang pernah kamu katakan tentang orang lain?",
    "Apa hal yang kamu suka lakukan bersama teman-teman yang tidak akan pernah kamu lakukan di depan pasanganmu?",
    "Siapa yang paling membuat kamu iri?",
    "Seperti apa piyama favoritmu?",
    "Pernahkah kamu berpura-pura sakit agar bisa keluar dari sebuah acara?",
    "Siapa orang tertua yang pernah kamu kencani?",
    "Berapa banyak swafoto yang kamu ambil dalam sehari?",
    "Apa batasanmu dalam sebuah hubungan yang tidak bisa ditolerir sama sekali?",
    "Berapa kali dalam seminggu kamu memakai celana yang sama?",
    "Apakah kamu akan berkencan dengan gebetanmu di SMA jika bertemu hari ini?",
    "Di bagian mana kamu merasa paling geli?",
    "Apakah kamu percaya pada takhayul? Jika ya, yang mana?",
    "Apa satu film yang kamu malu untuk akui bahwa kamu menikmatinya?",
    "Apa kebiasaan merawat dirimu yang paling memalukan?",
    "Kapan terakhir kali kamu meminta maaf? Untuk apa?",
    "Pernahkah kamu naksir berat pada seseorang yang jauh lebih tua atau lebih muda darimu?",
    "Dari mana sebagian besar bau memalukanmu berasal?",
    "Pernahkah kamu berpikir untuk selingkuh dari pasangan?",
    "Pernahkah kamu selingkuh dari pasangan?",
    "Celana dalam model boxer atau briefs?",
    "Pernahkah kamu buang air kecil di kolam renang?",
    "Apa tempat paling aneh di mana rambut pernah tumbuh di tubuhmu?",
    "Jika dijamin tidak akan pernah ketahuan, siapa di dunia ini yang akan kamu bunuh?",
    "Apa hadiah termurah yang pernah kamu berikan untuk orang lain?",
    "Aplikasi apa yang paling banyak membuang waktumu?",
    "Apa hal teraneh yang pernah kamu lakukan di pesawat?",
    "Pernahkah kamu telanjang di depan umum?",
    "Berapa banyak blog gosip yang kamu baca dalam sehari?",
    "Berapa usia pasangan termuda yang akan kamu kencani?",
    "Pernahkah kamu mengupil di depan umum?",
    "Pernahkah kamu berbohong tentang usiamu?",
    "Jika kamu harus menghapus satu aplikasi dari ponselmu, aplikasi apa itu?",
    "Apa pembelian larut malammu yang paling memalukan?",
    "Berapa lama waktu terpanjang kamu tidak mandi?",
    "Pernahkah kamu menggunakan KTP palsu?",
    "Siapa hall pass kamu? (Selebriti yang diizinkan untuk dikencani)",
    "Anggota keluargamu yang mana yang paling mengganggumu dan mengapa?",
    "Apa ketakutan terbesarmu dalam suatu hubungan?",
    "Apa kekesalan terbesarmu tentang orang di sebelah kirimu?",
    "Apa teks paling memalukan di ponselmu saat ini?",
    "Pernahkah kamu melihat mayat?",
    "Selebriti mana yang menurutmu terlalu dibesar-besarkan?",
    "Pernahkah kamu berbohong kepada atasanmu?",
    "Pernahkah kamu mencuri sesuatu dari tempat kerja?",
    "Berapa lama waktu terpanjang kamu tidak sikat gigi?",
    "Apa penyesalan terbesarmu dalam hidup?",
    "Siapa yang paling kamu benci lihat telanjang?",
    "Jelaskan hal teraneh yang pernah kamu lakukan saat mabuk.",
    "Apa satu hal dalam hidupmu yang ingin kamu ubah?",
    "Jika kamu bisa mengencani dua orang sekaligus, apakah kamu akan melakukannya? Jika ya, siapa?",
    "Apa hal yang akan membuatmu mati jika ibumu mengetahuinya?",
    "Apa hal paling menakutkan yang pernah terjadi padamu?",
    "Jika kamu bisa menjodohkan siapa pun di sini dengan sahabatmu, siapa orangnya dan mengapa?",
    "Seberapa sering kamu mencuci seprai?",
    "Pernahkah kamu kentut di lift?",
    "Siapa cinta pertamamu?",
    "Apa hal paling berdosa yang pernah kamu lakukan di tempat ibadah?",
    "Siapa yang akan kamu telepon untuk membantu mengubur mayat?",
    "Siapa yang akan meneleponmu untuk membantu mengubur mayat? Apakah kamu akan melakukannya?",
    "Kapan terakhir kali kamu menangis, dan mengapa?",
    "Apa barang milikmu yang paling berharga?",
    "Pernahkah ada yang masuk saat kamu di kamar mandi?",
    "Apa ketakutan masa kecilmu yang terbesar?",
    "Apa huruf pertama dari nama gebetanmu?",
    "Apa nilai terburuk yang pernah kamu dapatkan untuk sebuah mata pelajaran?",
    "Apa kebohongan terbesar yang pernah kamu katakan?",
    "Pernahkah kamu memecahkan barang mahal?",
    "Apa satu hal yang akan kamu ubah dari penampilanmu jika bisa?",
    "Jika kamu tiba-tiba punya satu juta dolar, bagaimana kamu akan menghabiskannya?",
    "Siapa guru terbaik yang pernah kamu miliki dan mengapa?",
    "Apa makanan terburuk yang pernah kamu cicipi?",
    "Apa cara paling aneh kamu bertemu seseorang yang sekarang kamu anggap teman dekat?",
    "Apa postingan paling memalukan yang pernah kamu unggah di media sosial?",
    "Siapa selebriti pertama yang kamu taksir?",
    "Pernahkah kamu membocorkan rahasia teman kepada orang lain?",
    "Berapa banyak anak yang ingin kamu miliki suatu hari nanti?",
    "Jika kamu hanya bisa makan satu jenis makanan seumur hidup, apa itu?",
    "Apa rahasia yang kamu miliki saat kecil yang tidak pernah kamu ceritakan kepada orang tuamu?",
    "Apa buku favoritmu sepanjang masa?",
    "Apa isi pesan teks terakhir yang kamu kirim ke sahabatmu?",
    "Secara kepribadian, kamu lebih mirip ibumu atau ayahmu?",
    "Pernahkah kamu melaporkan seseorang karena melakukan kesalahan (baik ke polisi atau di tempat kerja/sekolah)?",
    "Jika rumahmu terbakar dan kamu hanya bisa menyelamatkan tiga barang (selain orang), apa saja itu?",
    "Jika kamu bisa memilih satu pemain lain untuk diajak ke pulau terpencil, siapa orangnya?",
    "Olahraga atau hobi apa yang kamu harap kamu tekuni sejak kecil?",
    "Pernahkah kamu mencuri sesuatu?",
    "Pernahkah kamu diusir dari toko, restoran, bar, atau acara?",
    "Apa kencan terburuk yang pernah kamu alami?",
    "Apa hal teraneh yang pernah kamu lakukan di depan umum?",
    "Apa alasan terakhir yang kamu gunakan untuk membatalkan janji?",
    "Apa kesalahan terbesar yang pernah kamu buat di sekolah atau tempat kerja?",
    "Pemain mana yang akan bertahan paling lama dalam film horor/kiamat, dan siapa yang akan mati pertama?",
    "Apa ruangan/area paling kotor di rumahmu?",
    "Kapan terakhir kali kamu membuat orang lain menangis?",
    "Selain ponselmu, apa satu barang di rumahmu yang tidak bisa kamu hidup tanpanya?",
    "Apa pertengkaran terbesar yang pernah kamu alami dengan seorang teman?",
    "Apa fantasi terbesarmu?",
    "Siapa orang terakhir yang kamu cari di Instagram?",
    "Apa yang menjadi pemicu putusnya hubunganmu?",
    "Apa rahasia yang belum pernah kamu ceritakan kepada siapa pun?",
    "Apakah kamu punya bakat terpendam?",
    "Pernahkah kamu selingkuh dalam ujian?",
    "Jika kamu akan tampil di acara TV realitas, acara apa itu?",
    "Apa rasa tidak aman terbesarmu?",
    "Apa satu hal yang kamu benci orang lain tahu tentangmu?",
    "Apa hal terburuk yang pernah dilakukan seseorang padamu?",
    "Apa hal terbaik yang pernah dilakukan seseorang untukmu?",
    "Apa kebiasaan terburukmu?",
    "Apa kesalahpahaman terbesar tentang dirimu?",
    "Bagaimana kamu menilai penampilanmu dalam skala 1 sampai 10?",
    "Selebriti mana yang kamu kagumi?",
    "Jika kamu bisa menjadi satu selebriti selama sehari, siapa orangnya?",
    "Jika kamu bisa melakukan pekerjaan apa pun di dunia, apa itu?",
    "Seperti apa kehidupan impianmu?",
    "Apa yang paling kamu hargai - uang, ketenaran, kesuksesan, teman, keluarga, dll?",
    "Apa red flag terbesarmu pada pasangan?",
    "Jika kamu harus menikahi seseorang di ruangan ini, siapa orangnya dan mengapa?",
    "Artis musik mana yang diam-diam menurutmu terlalu dibesar-besarkan?",
    "Apa pendapat politikmu yang paling kontroversial?",
    "Sebutkan sesuatu yang tidak bisa kamu hidup tanpanya.",
    "Di mana kamu melihat dirimu dalam lima tahun ke depan?",
    "Apa yang ada di daftar putar 'On Repeat' Spotify-mu saat ini?",
    "Seberapa baik menurutmu kamu akan bertahan dalam film horor?",
    "Berapa banyak boneka binatang yang kamu miliki?",
    "Pernahkah kamu mendapat masalah di sekolah? Dan jika ya, untuk apa?",
    "Apakah kamu punya fobia?",
    "Siapa orang terakhir yang kamu cium?",
    "Jika kamu bisa menikahi selebriti mana pun, siapa orangnya dan mengapa?",
    "Apa bahasa cintamu? (love language)",
    "Siapa di buku teleponmu yang paling tidak ingin kamu telepon sekarang?",
    "Siapakah 'The One That Got Away' bagimu?",
    "Apakah kamu punya kembaran selebriti?",
    "Apa lima film yang paling sering kamu tonton?",
    "Seberapa mabuk paling parah yang pernah kamu alami?",
    "Apa hal paling menjijikkan yang pernah kamu lakukan?",
    "Apa hal paling memalukan yang pernah kamu lakukan di taksi?",
    "Apa alasan paling konyol kamu meninggalkan klub lebih awal?",
    "Ceritakan tentang ciuman pertamamu.",
    "Kapan waktu paling tidak pantas kamu kentut?",
    "Siapa yang menurutmu berpakaian paling buruk di ruangan ini?",
    "Pernahkah kamu berlatih ciuman di cermin?",
    "Apa momen fesyen terburukmu?",
    "Apa kekesalan terbesarmu (pet peeve)?",
    "Apa kombinasi makanan menjijikkan favoritmu?",
    "Apa kebohongan paling aneh yang pernah kamu katakan?",
    "Apakah kamu punya akun media sosial palsu?",
    "Apa yang memberimu 'the ick' (rasa ilfeel)?",
    "Apa yang kamu lakukan yang bisa memberi orang lain 'the ick'?",
    "Apa hal aneh yang kamu sukai di TikTok?",
    "Apa hal paling mengejutkan di tasmu sekarang?",
    "Siapa gebetan selebritimu yang aneh?",
    "Apa hal terburuk yang pernah kamu lakukan di tempat kerja?",
    "Apakah kamu punya fetish?",
    "Apa hal terburuk yang pernah kamu lakukan?",
    "Apa pendapatmu tentang poliamori?",
    "Apa pengalaman intim terburuk yang pernah kamu alami?",
    "Apa kencan terbaik yang pernah kamu jalani?",
    "Apa yang terjadi pada malam terakhir kamu keluar?",
    "Pernahkah kamu mengatakan sesuatu yang kamu sesali tentang seseorang di ruangan ini?",
    "Pernahkah kamu berbohong untuk keluar dari kencan yang buruk?",
    "Apa masalah terbesar yang pernah kamu hadapi?",
    "Kapan terakhir kali kamu berhubungan seks di luar ruangan?",
    "Apa kebohongan terburuk yang pernah kamu katakan?",
    "Apa satu hal yang kamu harap kamu berbohong tentangnya?",
    "Jika kamu harus memutuskan satu teman dari hidupmu, siapa orangnya?",
    "Apa kesenangan terlarangmu (guilty pleasure)?",
    "Apakah kamu pernah membocorkan rahasia mantanmu?",
    "Maukah kamu meninggalkanku demi orang yang lebih baik? Apa alasannya?",
    "Apakah kamu naksir seseorang di tempat kerja?",
    "Jika aku meninggal, berapa lama kamu akan menunggu untuk mendapatkan pasangan baru?",
    "Apakah kamu menerimaku apa adanya?",
    "Jika ternyata aku memiliki kekurangan yang jauh dari ekspektasimu, bagaimana cara kamu menyikapinya?",
    "Bagaimana jika kelak kita diharuskan untuk menjalin hubungan jarak jauh?",
    "Bagaimana responsmu, ketika aku didekati oleh orang lain?",
    "Kalau mantanku mendekatiku lagi, apa yang akan kamu lakukan?",
    "Sampai kapan kamu akan mencintaiku?",
    "Apa yang kamu harapkan dari hubungan kita?",
    "Seberapa penting kesetiaan bagi kamu?",
    "Jika kelak aku tertimpa musibah dan mengalami kerugian berarti, apa yang akan kamu lakukan?",
    "Pernah cemburu berat? Apa yang bikin kamu cemburu?",
    "Apa nama kontakku di ponselmu?",
    "Apa kamu puas dengan hubungan kita saat ini?",
    "Apa hal paling berat dalam menjalani hubungan denganku?",
    "Apakah kamu mau jadi pasanganku selamanya? Apa rencana masa depanmu denganku?",
    "Bagaimana perasaanmu jika sedang bersama denganku?",
    "Apa yang ingin kamu wujudkan dari hubungan kita?",
    "Menurut kamu aku ini orangnya seperti apa?",
    "Menurut kamu apa kekuranganku?",
    "Apa bukti kalau kamu memang sayang sama aku?",
    "Kamu nggak pernah capek kan jalanin hubungan ini? Apa alasannya?",
    "Pernah kesal dengan aku, tapi kamu memilih bungkam nggak? Kalau ada tentang apa?",
    "Apakah ada aspek hubungan kita yang perlu diperbaiki?",
    "Apa yang membuat kamu bertahan dengan aku?",
    "Pasangan seperti apa yang kamu idamkan sebagai pendamping hidupmu?",
    "Adakah seseorang yang akhir-akhir ini intens kamu chat?",
    "Apa yang paling kamu tidak bisa lupakan dari mantan?",
    "Apakah punya mantan terindah? Siapa?",
    "Apakah kamu masih ingat sama mantan-mantan kamu? Apa yang paling kamu ingat dari mantan-mantanmu?",
    "Apakah kamu pernah diajak balikan sama mantan?",
    "Bagaimana pendapatmu kalau diajak bertemu lagi dengan mantan?",
    "Jika kamu harus kembali dengan mantan, siapa yang akan kamu pilih?",
    "Siapa mantan yang paling kamu benci?",
    "Kebiasaan baik mantan yang paling kamu ingat?",
    "Kebiasaan buruk mantan yang paling kamu ingat?",
    "Apakah kamu pernah kena friendzone?",
    "Apakah kamu pernah memberikan harapan ke seseorang?",
    "Apakah kamu pernah mengalami cinta bertepuk sebelah tangan?",
    "Apakah kamu pernah ditikung oleh sahabat?",
    "Apakah kamu pernah suka sama sahabat sendiri?",
    "Siapa orang yang pernah kamu sukai diam-diam?",
    "Apakah kamu masih stalking mantan di Instagram?",
    "Siapa mantan yang sering kamu stalk di Instagram?",
    "Acara TV apa yang paling kamu benci? Beri tahu alasannya!",
    "Kapan terakhir kali kamu kentut?",
    "Apakah kamu pernah melanggar hukum?",
    "Apa hal yang membuatmu senang orang tuamu tidak mengetahuinya?",
    "Siapa orang yang paling ingin kamu cium di antara kita?",
    "Apa penyesalan terburukmu?",
    "Kenapa kamu putus dengan mantan yang sebelumnya?",
    "Apa fantasi terbesar atau teranehmu?",
    "Apakah kamu masih memiliki perasaan untuk salah satu mantanmu?",
    "Lebih suka dijemput naik mobil yang harganya murah atau naik motor mahal?",
    "Apa lima hal terbaru dalam riwayat pencarian di browser?",
    "Apa rahasia yang kamu sembunyikan dari orang tua?",
    "Jika dapat uang Rp 1 miliar sekarang juga, hal pertama yang kamu mau beli apa?",
    "Jika kamu harus mengubah namamu, apa nama yang kamu inginkan?",
    "Seberapa sering nonton film porno? Kapan terakhir kali melakukan hal tersebut?",
    "Di antara orang disini siapa yang paling memiliki sifat buruk dan siapa yg paling memiliki sifat baik?",
    "Pilih salah satu, keluar rumah tanpa pakai celana dalam atau tidak mandi 1 bulan?",
    "Apakah kamu pernah mencoba mengambil foto selfie diri sendiri dengan gaya seksi?",
    "Berapa nilai (pilih salah satu teman) dari 1-5 dari style-nya?",
    "Kalau kamu tiba-tiba bisa menghilang, apakah hal pertama yang akan kamu lakukan?",
    "Hal gila apa yang pernah kamu lakukan untuk mengikuti tren media sosial?",
    "Makanan apa yang pernah kamu makan, namun seharusnya tidak dimakan?",
    "Apa hal yang paling konyol yang kamu percaya sejak kecil?",
    "Apa hal gila yang pernah kamu lakukan malam hari?",
    "Benda aneh apa yang kamu pernah bawa di dalam tasmu?",
    "Barang aneh apa yang kamu beli tapi tidak berguna dan berujung menjadi impulsif?",
    "Hal gila apa yang pernah kamu pertaruhkan untuk taruhan?",
    "Apa kebiasaan gila dan buruk yang kamu miliki?",
    "Apakah kamu pernah menyatakan cinta pada siswa/siswi populer di sekolah?",
    "Hal paling kekanak-kanakan apa yang pernah kamu lakukan di atas usia 17 tahun?",
    "Siapa yang lagi kamu taksir sekarang?",
    "Jika diberi kesempatan pacaran dengan semua orang, siapa yang paling ingin kamu pacari?",
    "Apakah kamu pernah naksir gurumu saat di sekolah?",
    "Lebih pilih jelek tapi kaya harta, atau ganteng/cantik tapi miskin?",
    "Hal apa yang tidak kamu sukai tentang pacarmu?",
    "Siapakah orang yang tidak kamu sukai, tapi mesti pura-pura suka?",
    "Siapakah satu orang yang kamu harap masih ada dalam hidup kamu?",
    "Pernah salah sebut nama orang saat di jalan? Ceritain, dong!",
    "Apa satu hal yang kamu ingin orang lain tahu tentangmu?",
    "Berapa banyak uang yang kamu habiskan saat kencan pertama?",
    "Apa kamu suka cowok wibu?",
    "Apa satu hal yang hanya kamu lakukan saat sendirian?",
    "Apa mimpi teraneh yang pernah kamu alami?",
    "Siapa namaku di daftar kontak WhatsApp-mu?",
    "Hal apa yang membuat kamu tertarik pada lawan jenis?",
    "Apa yang paling kamu tidak bisa lupakan dari mantan terakhir?",
    "Apakah kamu pernah diajak balikan oleh mantan?",
    "Siapa yang paling sering kamu kirimi pesan teks?",
    "Siapa orang terakhir yang kamu katakan \"Aku mencintaimu\"?",
    "Pernahkah kamu kepergok selingkuh?",
    "Kamu pilih teman jelek tapi kaya atau cantik tapi miskin?",
    "Jika kamu hanya bisa mencapai tiga hal dalam hidup, apa saja yang ingin dicapai?",
    "Ceritakan tentang kegagalan romantis terbesar yang pernah kamu alami.",
    "Pernahkah kamu diselingkuhi? Kapan dan oleh mantan yang keberapa?",
    "Jujur, siapa orang yang kamu suka saat SMA?",
    "Siapa sosok orang yang kamu dambakan ketika di SMA?",
    "Adakah orang yang kamu suka ketika duduk di bangku kuliah?",
    "Siapa orang yang paling kamu suka ajak ngobrol sampai larut malam?",
    "Kapan terakhir kali kamu overthinking?",
    "Pernah terbayangkan nggak kamu ingin resign dari kerjaan? Kenapa alasannya?",
    "Pernah nyanyi-nyanyi sendiri nggak pas lagi bawa motor?",
    "Pernah nggak salah kirim chat di WhatsApp? Kalau iya ke siapa?",
    "Apa hadiah paling aneh yang pernah kamu terima di hari ulang tahunmu?",
    "Apa hal paling memalukan yang pernah kamu lakukan di depan orang tua atau keluarga?",
    "Pernahkah kamu membuat seseorang marah karena salah memahami sesuatu yang kamu katakan?",
    "Jika kamu bisa mengganti namamu dengan nama kartun, apa yang akan kamu pilih dan kenapa?",
    "Apa kebiasaan unik yang kamu miliki saat makan?",
    "Pernahkah kamu terjebak dalam situasi canggung? Ceritakan momen tersebut.",
    "Lagu terakhir yang didenger?",
    "Masih simpen foto mantan ga?",
    "Pernah berapa kali ciuman bibir sama lawan jenis selain keluarga?",
    "Belanjaan paling disesalin?",
    "Siapa yang pengen kamu hidupkan dan bunuh?",
    "Quotes hidup kamu?",
    "Hal paling egois apa yang kamu lakukan?",
    "First impression semua yang main TOD ini!",
    "Hal termahal apa yang pernah kamu beli?",
    "Paling takut sama apa?",
    "Kejahatan yang pernah kamu lakukan?",
    "Film horor favorit?",
    "Pengen dilamar gimana?",
    "Siapa orang yang kamu pengen jadiin pacar?",
    "Obat yang paling sering kamu konsumsi?",
    "Bunga kesukaan?",
    "Bakat aneh yang kamu punya?",
    "Pernah kepergok pas ngapain?",
];
const dares = [
    "Makan camilan tanpa menggunakan tangan sama sekali.",
    "Tunjukkan gerakan tarian terbaik (atau terburuk) yang kamu miliki selama 1 menit.",
    "Tirukan suara dan gerakan hewan favoritmu selama 30 detik.",
    "Nyanyikan lagu anak-anak (misalnya \"Balonku Ada Lima\") dengan ekspresi dan semangat penuh seolah-olah sedang konser rock.",
    "Menjadi patung dan tidak boleh bergerak sama sekali selama satu putaran permainan penuh, apa pun yang terjadi.",
    "Berbicaralah dengan aksen asing (misalnya, Inggris, India, atau daerah) yang dipilih oleh pemain lain selama 5 menit.",
    "Ulangi setiap kata yang diucapkan oleh orang di sebelah kananmu sampai giliranmu berikutnya tiba.",
    "Serahkan ponselmu ke salah satu pemain dan biarkan dia mengirim satu pesan bebas ke siapa pun di daftar kontakmu.",
    "Kirim pesan teks ke gebetanmu sekarang juga dan katakan, \"Aku dari dulu naksir kamu, kamu mau jadi pacarku?\". Tunjukkan balasannya.",
    "Unggah foto paling aib dari galeri ponselmu ke Instagram Story dengan caption \"Inilah aku apa adanya\". Biarkan selama 10 menit.",
    "Telepon orang tuamu dan dengan nada serius katakan, \"Ayah/Ibu, aku mau kabur dari rumah!\".",
    "Lakukan check out pada barang teratas yang ada di keranjang belanja e-commerce-mu saat ini juga.",
    "Buat video TikTok menirukan salah satu tren tarian yang sedang viral dan unggah ke akunmu.",
    "Ubah nama kontak pasangan atau teman terdekatmu di ponsel menjadi sesuatu yang memalukan (misalnya, \"Ratu Drama\" atau \"Tukang Utang\") dan tunjukkan buktinya.",
    "Pergi ke luar rumah dan berteriak sekeras yang kamu bisa, \"AKU JATUH CINTA!\"",
    "Minta seorang pejalan kaki yang tidak kamu kenal untuk menilai penampilanmu dari skala 1 hingga 10.",
    "Berdiri di depan gerbang rumah dan sapa setiap orang yang lewat dengan lambaian tangan dan senyuman selama lima menit penuh.",
    "Ajak bicara seorang pedagang kaki lima yang lewat dengan menggunakan bahasa Inggris sebisamu.",
    "Nyanyikan lagu kebangsaan \"Indonesia Raya\" dengan suara lantang di tempat umum (misalnya, teras rumah atau pinggir jalan).",
    "Datangi tetangga terdekat dan pinjam barang yang tidak masuk akal, seperti garam sebanyak satu sendok teh atau satu lembar tisu.",
    "Makan satu siung bawang putih mentah utuh tanpa minum.",
    "Cium kaus kaki kotor milik salah satu pemain di ruangan ini.",
    "Biarkan pemain lain menuangkan segelas air es ke kepalamu.",
    "Minum satu sendok makan kecap asin atau cuka langsung dari botolnya.",
    "Simpan tiga buah es batu di dalam mulutmu dan biarkan mencair sepenuhnya tanpa dikunyah atau ditelan.",
    "Biarkan pemain lain menggambar sesuatu di wajahmu dengan spidol permanen.",
    "Makan sesendok sambal atau saus paling pedas yang tersedia.",
    "Tunjukkan lima hal terakhir dalam riwayat pencarian di peramban internetmu.",
    "Pernahkah kamu menutupi kesalahan besar yang akhirnya membuat orang lain yang disalahkan? Ceritakan!",
    "Apa hal paling gila yang pernah kamu pikirkan saat sendirian tapi tidak akan pernah berani kamu lakukan?",
    "Kirim lirik lagu ke seseorang, baris demi baris.",
    "Hubungi orang pertama di daftar kontak kamu dan nyanyikan \"Selamat Ulang Tahun\" buat mereka.",
    "Serahkan ponsel kamu ke pemain lain dan biarkan mereka mengirim DM ke siapa pun di media sosial.",
    "Lakukan push-up sebanyak yang kamu bisa dalam satu menit.",
    "Biarkan pemain lain menuang segelas air ke kepala kamu.",
    "Unggah swafoto yang tidak menarik ke akun media sosial favoritmu.",
    "Bicara dan bertindak seperti selebriti sampai giliran kamu selesai.",
    "Buat rap freestyle selama satu menit tentang pemain lain.",
    "Berdansa tanpa musik selama satu menit.",
    "Bicaralah tanpa menutup mulut.",
    "Nyanyikan lagu kebangsaan dengan aksen Inggris.",
    "Tiru kembali foto paling memalukan yang pernah kamu ambil.",
    "Kirim swafoto wajah bebek ke nomor acak di ponselmu.",
    "Tiru gaya atau perilaku seseorang di kelompok ini.",
    "Mengumpat terus-menerus selama 30 detik.",
    "Buat puisi tentang hewan peliharaan keluargamu.",
    "Gigit sepotong lemon tanpa ekspresi.",
    "Biarkan tiga es batu meleleh di dalam mulut kamu tanpa dikunyah.",
    "Buat ekspresi seperti habis makan sesuatu yang tidak enak, dan tahan sampai giliran kamu berikutnya.",
    "Lakukan tarian perut selama 30 detik.",
    "Minta seseorang yang tidak kamu kenal untuk menilai kamu dari skala 1–10.",
    "Tunjukkan semua isi dompet atau tas kamu ke kami.",
    "Keluar dan nyanyikan lagu kebangsaan dengan suara lantang.",
    "Kirim pesan \"Selamat Ulang Tahun\" ke mantan kamu.",
    "Kirim pesan ke gebetan kamu sekarang.",
    "Hubungi seseorang yang sudah lama tidak kamu hubungi, namun orang tersebut penting untuk kamu!",
    "Tulis sebuah tulisan untuk dirimu sendiri dan bacakan di depan teman-teman kamu agar dapat selalu diingat!",
    "Tunjukkan riwayat pencarian terakhir di media sosialmu.",
    "Kirim pesan suara ke kontak acak yang isinya, \"Bro/Kak, traktiran kopinya ditunggu ya minggu ini.\"",
    "Biarkan orang di sebelahmu menulis caption Instagram-mu dan langsung posting.",
    "Ganti nama kontak \"Mama\" jadi \"Bestie Tercinta\" dan screenshot.",
    "Duduk di lantai dan ceritakan kisah hidupmu dalam 30 detik seolah-olah kamu sedang di film dokumenter.",
    "Gunakan salah satu properti yang ada (topi, selimut, dll) dan berpura-pura menjadi pembawa berita.",
    "Ketik \"aku sayang kamu\" ke teman SMP yang sudah lama tidak dihubungi, screenshot!",
    "Selama 3 menit, kamu hanya boleh menjawab \"Ya ampun, serius?\" untuk semua pertanyaan.",
    "Buat tantangan TikTok dadakan bersama 2 orang di ruangan ini.",
    "Katakan pada salah satu temanmu, \"Bro, gue punya rahasia besar... tapi jangan bilang siapa-siapa ya,\" lalu diam.",
    "Pura-pura jadi guru galak dan nilai pakaian semua orang di ruangan ini.",
    "Ambil swafoto dengan pose paling aneh dan kirim ke story WA.",
    "Pura-pura jadi stand-up comedian dan kasih satu lelucon soal hidup kamu.",
    "Bilang ke orang random (atau tamu lain di rumah/kos), \"Kamu pernah muncul di mimpi saya.\"",
    "Lakukan gerakan olahraga ala influencer selama 1 menit penuh.",
    "Selama 5 menit, kamu harus berjalan mundur ke mana pun kamu pergi.",
    "Tulis status: \"Pacarku paling imut sedunia\" di story-mu, biarkan selama 10 menit.",
    "Ucapkan \"aku cinta kamu\" 5 kali padaku, tapi setiap kalimat harus dengan suara karakter kartun yang berbeda.",
    "Coba tebak hal kecil yang membuatku paling bahagia saat kita bersama. Kalau salah, kamu harus menyanyikan lagu cinta!",
    "Pura-pura baru saja melamarku dan rayu aku sampai aku tertawa. Poin plus kalau pakai properti seadanya!",
    "Gambar wajahku (atau sesuatu yang menurutmu mewakili aku) dengan spidol di tanganmu. Tidak boleh dihapus sampai permainan selesai.",
    "Kirimi aku pesan suara 10 detik berisi gombalan paling absurd yang bisa kamu pikirkan.",
    "Sebutkan 3 hal yang kamu suka dariku, tapi dengan gaya komentator bola.",
    "Gunakan benda di sekitarmu, lalu jelaskan kenapa benda itu cocok jadi simbol hubungan kita.",
    "Akui, apa mimpi teraneh yang pernah kamu alami tentang aku? Ceritakan sekarang.",
    "Peragakan ulang pertemuan pertama kita, versimu, tapi harus lebay dan dramatis seperti sinetron.",
    "Sebutkan 3 nama panggilan sayang untukku yang belum pernah kamu pakai sebelumnya. Salah satunya harus dipakai sampai permainan selesai.",
    "Buat aku tertawa dalam 1 menit. Kalau gagal, kamu harus melakukan tarian TikTok paling cringe.",
    "Ambil lagu romantis, lalu ganti liriknya jadi tentang kita. Nyanyikan juga, jangan cuma dibaca!",
    "Tutup matamu, lalu aku akan memberimu ciuman di salah satu bagian wajahmu — kamu harus tebak di mana. Kalau salah, ulangi!",
    "Goda aku seolah-olah kamu baru pertama kali mengajakku kenalan. Tapi, kamu harus pakai logat daerah (bebas pilih).",
    "Video dirimu menyanyikan lagu kebangsaan dengan gaya rock sejati dan unggah ke story-mu (biarkan 15 menit).",
    "Telepon kontak acak (siapa saja) dan pura-pura mengundang mereka untuk bergabung dengan bisnis MLM.",
    "Baca isi DM atau chat terakhir dari seseorang yang namanya diawali huruf \"S\" dengan suara dramatis.",
    "Screenshot galeri ponselmu (tampilan grid 9 foto terakhir) dan tunjukkan ke semua orang.",
    "Makan sesendok penuh sambal atau saus acak dari kulkas.",
    "Tunjuk satu orang di ruangan ini dan katakan padanya \"Kamu membuat jantungku berdebar sejak awal\" dengan ekspresi serius.",
    "Ganti nama kontak pasangan/teman dekat di ponselmu menjadi \"Tuan\" atau \"Ratu Galak\" selama sisa permainan.",
    "Ceritakan secara detail mimpi teraneh yang kamu ingat... tanpa sensor.",
    "Berdiri, tutup mata, dan biarkan orang acak meletakkan satu benda di tanganmu. Kamu harus menebak apa itu, jika salah dua kali, makan satu gigitan makanan acak.",
    "Unggah foto dirimu dengan caption: \"Aku baru sadar... aku sangat suka Hello Kitty.\"",
    "Tanya orang di sebelahmu, \"Menurutmu, aku lebih cocok jadi antagonis atau protagonis dalam hidupmu?\" Kamu harus menerima jawaban mereka.",
    "Tunjuk 2 orang, terus bilang, \"Kalian cocok jadi pasangan!\" dan kasih alasan kenapa (bebas, tapi harus meyakinkan).",
    "Baca 5 pesan terakhir dari notifikasi kamu, terus bacakan dengan gaya penyiar radio galau.",
    "Ambil swafoto dengan pose paling jelek dan kirim ke grup chat keluarga. Screenshot buktinya.",
    "Pergi ke luar sebentar (jika di tempat umum atau bisa mengakses luar), lalu teriak: \"Aku cinta kamu, dunia!\" dengan keras.",
    "Plank selama 1 menit penuh.",
    "Harus menuruti semua perkataan satu orang pemain selama 20 menit ke depan.",
    "Telepon orang yang dipilih seorang pemain dan nyanyikan lagu Happy Birthday.",
    "Push-up sekali setiap ada orang yang bilang \"aku\" selama 10 menit ke depan.",
    "Makan sayuran mentah pertama yang terlihat di kulkas.",
    "Teriakkan kata pertama yang terlintas dalam pikiranmu.",
    "Tutup hidungmu saat menyanyikan lagu favorit.",
    "Telepon ayahmu dan bilang kamu ingin menikah.",
    "Tutup matamu sampai giliran selanjutnya.",
    "Berikan pijatan kaki pada orang di sebelah kananmu.",
    "Lelehkan es di punggung orang di sebelahmu.",
    "Lakukan 100 kali squat.",
    "Tunjukkan foto paling memalukan di ponselmu.",
    "Baca 5 pesan terakhir di ponselmu.",
    "Coba jilat siku kamu.",
    "Berpura-pura menjadi orang di sebelah kirimu selama 15 menit.",
    "Tiru orang di sebelah kananmu.",
    "Merangkak di sekitar ruangan.",
    "Menari perut dengan musik Maroko.",
    "Lakukan rap freestyle selama 1 menit tentang peserta lain.",
    "Cium orang di sebelah kirimu.",
    "Lakukan gerakan cartwheel.",
    "Biarkan orang di sebelah kananmu menggambar di wajahmu.",
    "Tangkap layar riwayat pencarian internet kamu.",
    "Tunjukkan chat terakhirmu dengan pasangan/gebetan.",
    "Telepon temanmu secara acak dan bilang, \"Bisa bantu?\".",
    "Ambil swafoto dan unggah ke Instastory dengan gaya paling jelek yang bisa kamu lakukan.",
    "Tepuk bahu orang asing yang lewat secara acak dan katakan, \"Hai, bro!\".",
    "Minta foto dari seseorang yang kamu temui di jalan.",
    "Biarkan wajahmu dirias secara acak.",
    "Berdiri di luar dan sapa semua orang yang kamu lihat.",
    "Lanjutkan permainan sambil jongkok sampai ada orang lain yang kalah.",
    "Buat Instastory menggunakan filter yang paling kamu benci.",
    "Chat orang pertama di daftar Instastory-mu dengan mengatakan, \"Aku tahu rahasiamu selama ini.\"",
    "Unggah salah satu foto favorit gebetanmu.",
    "Jilat sikumu tanpa bantuan tangan satunya.",
    "Keluarkan semua isi tas dan dompetmu.",
    "Pilih seseorang dan lakukan tarian lucu di depannya.",
    "Nyanyikan lagu karaoke yang sedang hits dengan nada tinggi.",
    "Telepon nomor acak dan nyanyikan \"Selamat Ulang Tahun.\"",
    "Ganti nama profil media sosialmu menjadi sesuatu yang aneh dan biarkan selama satu jam.",
    "Lakukan lip sync lagu populer tanpa musik.",
    "Masuk ke dalam lemari atau ruangan terpencil selama 5 menit tanpa lampu atau ponsel.",
    "Berjalan jongkok mengelilingi ruangan selama 1 menit.",
    "Cium orang yang kamu suka.",
    "Buatlah koreografi tarian modern di depan teman-temanmu!",
    "Buat cerita dari 3 kata kunci yang teman-temanmu berikan!",
    "Telepon satu teman lawan jenis dan katakan bahwa dia adalah orang yang cantik atau ganteng yang pernah kamu temukan!",
    "Bernyanyilah lagu apapun dan tambahkan gerakan tarian!",
    "Katakan \"aku cantik atau aku ganteng\" dan biarkan temanmu membuat status atau postingan mengenai dirimu!",
    "Kirim temanmu foto selfie yang menurutmu aib!",
    "Pergi keluar pintu atau keluar pagar dan nyanyikan lagu \"Let It Go\" dari film Frozen!",
    "Gunakan nada pada setiap omonganmu selama 3 putaran permainan!",
    "Nyanyikan lagu Indonesia Raya dan unggah pada media sosial!",
    "Gunakan baju yang saat ini kamu pakai, namun dengan keadaan terbalik selama 5 putaran permainan!",
    "Telepon orang tua dan katakan \"aku mau kabur dari rumah\"!",
    "WhatsApp pacarmu atau kekasihmu dan katakan \"kamu selingkuh ya?\"!",
    "Coba telepon atau chat seseorang yang kamu taksir atau naksir kamu.",
    "Telepon teman secara acak dan katakan \"Ada apa meneleponku?\"",
    "Pesan makanan di aplikasi, lalu kasih tip sopirnya sesuai jumlah baterai ponselmu.",
    "Kirim pesan ke orang yang kamu sukai dan ajak dia kencan.",
    "Pilih nomor ketiga pada daftar kontak kamu dan kirimi mereka puisi konyol.",
    "Berjalan mengelilingi kompleks perumahan kamu dan berbicara sendiri sepanjang waktu, terutama saat lagi banyak orang.",
    "Kirimkan tangkapan layar pesanmu dengan orang terakhir selain aku.",
    "Kirim pesan ke mantan terindah dan bilang kalau kamu masih punya perasaan padanya.",
    "Hubungi mantan kamu dan katakan sesuatu yang buruk.",
    "Ceritakan hal memalukan yang dilakukan bersama mantan.",
    "Kirim foto terjelek kepada mantan.",
    "Kirimkan foto terbaru kamu dalam galeri ke grup sekolah.",
    "Minum segelas air tanpa menggunakan tangan.",
    "Makan kecap langsung dari botolnya.",
    "Unggah foto dengan pose alay ke media sosial.",
    "Telepon seorang teman dan nyanyikan lagu ulang tahun.",
    "Buat salah satu TikTok challenge yang viral.",
    "Ceritakan tentang saat kamu mempermalukan diri sendiri di depan orang yang kamu sukai.",
    "Kirim pesan secara acak ke salah satu teman di media sosial.",
    "Kirim pesan yang aneh kepada anggota keluargamu.",
    "Edit fotomu bersama gebetan, lalu pasang di media sosial.",
    "Bicara dengan gaya sangat genit!",
    "Chat pasanganmu dan bilang \"aku mau nikah secepatnya\".",
    "Chat mantan terindahmu lalu bilang \"kamu makin hari makin cantik aja setelah putus sama aku\".",
    "Pijitin kaki teman selama 10 menit.",
    "Makan sayur-sayuran mentah.",
    "Kupas kulit pisang pakai mulut.",
    "Tembak gebetan yang masih di tahap PDKT sekarang juga!",
    "Cari laki-laki atau perempuan di dating apps, kalau sudah match langsung ajak jalan.",
    "Makan mi instan dengan tingkat pedas level 10.",
    "Ajak tukang jualan yang lewat depan rumah pakai bahasa Inggris.",
    "Teriak keluar ruangan \"Hei pacar? Hei~ Hei Tayoo\".",
    "Nari India pake lagu Kuch Kuch Hota Hai.",
    "Impersonate Lucinta Luna.",
    "Nyanyi Dangdut keras-keras.",
    "Push up 5x.",
    "Bilang \"aku sayang kamu\" sambil tatap matanya dan jilat bibir ke orang paling tua di situ.",
    "Chat Ibu dan bilang I love you.",
    "Minum air botol tanpa napas.",
    "Twerking sambil tepuk pantat.",
    "Rayu mantan untuk balikan.",
    "Baca Ayat Kursi/Doa Kudus/sejenisnya.",
    "Roll depan (gymnastic).",
    "Nyanyi lagu rock pake gaya bolo-bolo.",
    "Nyanyi lagu balonku, huruf vokal jadi 'i' semua.",
    "Nyanyi lagu nasional sambil menghadap tembok kencang-kencang.",
    "Lipsync lagu galau sambil squad minimal 30 detik.",
    "Makan/Minum Ramuan aneh buatan teman.",
    "Perbarui status media sosialmu dengan berpura-pura menjadi diriku.",
    "Eja namamu dengan lidahmu di suatu tempat di tubuhku.",
    "Biarkan dirimu ditutup matanya dan diberi makan sesuatu pilihanku.",
    "Lakukan tiruan terbaikmu tentang diriku.",
    "Cium aku dengan penuh gairah selama lima menit.",
    "Siaran langsung di salah satu akun media sosialmu dan nyatakan cintamu padaku.",
    "Tutup matamu, pilih kontak acak di Whatsapp-mu dan tinggalkan pesan suara mesum untuk mereka.",
    "Ingat kembali hari/malam kita bertemu, dari sudut pandangmu.",
    "Gambar atau lukis sebuah gambar hanya dengan menggunakan kakimu.",
    "Posting selfie tertua yang ada di ponselmu di Instagram Stories.",
    "Biarkan aku mencukur sebagian tubuhmu.",
    "Tulis puisi cinta untukku dalam waktu lima menit atau kurang.",
    "Ambil sesuatu dari dapur dan coba memakannya dengan cara yang paling genit/seksi.",
    "Lihat berapa banyak es batu yang bisa kamu masukkan ke dalam mulutmu dan biarkan meleleh.",
    "Sampaikan stand-up terbaikmu selama lima menit.",
    "Biarkan aku merias wajahmu sambil ditutup matanya.",
    "Tukar pakaian denganku.",
    "Katakan ya untuk semuanya selama satu jam ke depan.",
    "Bacakan lima hal terakhir di riwayat pencarian Google-mu.",
    "Biarkan aku menggambar sesuatu di tubuhmu dengan spidol permanen.",
    "Telepon seseorang pilihanku dan nyanyikan selamat ulang tahun untuk mereka.",
    "Mandi dengan pakaian lengkap.",
    "Lepaskan tiga potong pakaian.",
    "Cium bagian favoritmu dari tubuhku.",
    "Lakukan tarian menggoda.",
    "Biarkan aku menggambarmu telanjang.",
    "Jilat sesuatu dari jariku.",
    "Lepaskan satu item pakaianku tanpa menggunakan tanganmu.",
    "Sebutkan tiga lagu yang akan kamu tambahkan ke daftar putar seks.",
    "Jatuhkan es batu ke dalam celana dalammu.",
    "Pergi ke ruangan lain, ambil foto seksi dan kirimkan padaku.",
    "Beri aku pijatan kaki selama lima menit.",
    "Biarkan aku memberimu pukulan ringan.",
    "Pergi tanpa pakaian dalam pada kencan kita berikutnya.",
    "Bacakan kutipan erotis dengan lantang.",
    "Peragakan kembali ciuman pertama kita.",
    "Tantang aku untuk perang bantal.",
    "Sembunyikan cokelat di pakaianmu dan biarkan aku menemukannya.",
    "Cium aku dengan penuh gairah selama lima menit.",
    "Siaran langsung di salah satu akun media sosialmu dan nyatakan cintamu padaku.",
    "Tutup matamu, pilih kontak acak di Whatsapp-mu dan tinggalkan pesan suara mesum untuk mereka.",
    "Ingat kembali hari/malam kita bertemu, dari sudut pandangmu.",
    "Gambar atau lukis sebuah gambar hanya dengan menggunakan kakimu.",
    "Posting selfie tertua yang ada di ponselmu di Instagram Stories.",
    "Biarkan aku mencukur sebagian tubuhmu.",
    "Tulis puisi cinta untukku dalam waktu lima menit atau kurang.",
    "Ambil sesuatu dari dapur dan coba memakannya dengan cara yang paling genit/seksi.",
    "Lihat berapa banyak es batu yang bisa kamu masukkan ke dalam mulutmu dan biarkan meleleh.",
    "Sampaikan stand-up terbaikmu selama lima menit.",
    "Biarkan aku merias wajahmu sambil ditutup matanya.",
    "Tukar pakaian denganku.",
    "Katakan ya untuk semuanya selama satu jam ke depan.",
    "Bacakan lima hal terakhir di riwayat pencarian Google-mu.",
    "Biarkan aku menggambar sesuatu di tubuhmu dengan spidol permanen.",
    "Telepon seseorang pilihanku dan nyanyikan selamat ulang tahun untuk mereka.",
    "Mandi dengan pakaian lengkap.",
    "Lepaskan tiga potong pakaian.",
    "Cium bagian favoritmu dari tubuhku.",
    "Lakukan tarian menggoda.",
    "Biarkan aku menggambarmu telanjang.",
    "Jilat sesuatu dari jariku.",
    "Lepaskan satu item pakaianku tanpa menggunakan tanganmu.",
    "Sebutkan tiga lagu yang akan kamu tambahkan ke daftar putar seks.",
    "Jatuhkan es batu ke dalam celana dalammu.",
    "Pergi ke ruangan lain, ambil foto seksi dan kirimkan padaku.",
    "Beri aku pijatan kaki selama lima menit.",
    "Biarkan aku memberimu pukulan ringan.",
    "Pergi tanpa pakaian dalam pada kencan kita berikutnya.",
    "Bacakan kutipan erotis dengan lantang.",
    "Peragakan kembali ciuman pertama kita.",
    "Tantang aku untuk perang bantal.",
    "Sembunyikan cokelat di pakaianmu dan biarkan aku menemukannya.",
];

export default function TruthOrDareGame() {
    const [gameState, setGameState] = useState('choice'); // 'choice' or 'result'
    const [resultType, setResultType] = useState('');
    const [resultText, setResultText] = useState('');
    const [lastTruthIndex, setLastTruthIndex] = useState(-1);
    const [lastDareIndex, setLastDareIndex] = useState(-1);
    const [isFlipping, setIsFlipping] = useState(false);

    const showResult = (type: 'truth' | 'dare') => {
        let text = '';
        let newIndex: number;

        if (type === 'truth') {
            do {
                newIndex = Math.floor(Math.random() * truths.length);
            } while (newIndex === lastTruthIndex && truths.length > 1);
            setLastTruthIndex(newIndex);
            text = truths[newIndex];
            setResultType('TRUTH');
        } else {
            do {
                newIndex = Math.floor(Math.random() * dares.length);
            } while (newIndex === lastDareIndex && dares.length > 1);
            setLastDareIndex(newIndex);
            text = dares[newIndex];
            setResultType('DARE');
        }

        setIsFlipping(true);
        setTimeout(() => {
            setResultText(text);
            setGameState('result');
            setIsFlipping(false);
        }, 400); // Halfway through the animation
    };

    const resetGame = () => {
        setGameState('choice');
    };

    return (
        <div className="w-full max-w-lg text-center font-nunito">
            <style jsx>{`
                .font-display { font-family: var(--font-poppins), sans-serif; }
                .neon-text { text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 20px #ff00de, 0 0 30px #ff00de, 0 0 40px #ff00de, 0 0 55px #ff00de, 0 0 75px #ff00de; }
                .btn-choice { transition: all 0.3s ease; border: 2px solid; text-transform: uppercase; letter-spacing: 2px; position: relative; overflow: hidden; }
                .btn-choice:before { content: ''; position: absolute; top: 0; left: -100%; width: 100%; height: 100%; transition: all 0.5s ease; z-index: 0; }
                .btn-choice:hover:before { left: 0; }
                .btn-truth { border-color: #00f7ff; color: #00f7ff; box-shadow: 0 0 15px rgba(0, 247, 255, 0.5); }
                .btn-truth:before { background: #00f7ff; }
                .btn-dare { border-color: #ff00de; color: #ff00de; box-shadow: 0 0 15px rgba(255, 0, 222, 0.5); }
                .btn-dare:before { background: #ff00de; }
                .btn-choice:hover { color: #1a1a2e; transform: translateY(-5px); box-shadow: 0 10px 20px rgba(0,0,0,0.2); }
                .btn-choice span { position: relative; z-index: 1; }
                #card { background: rgba(255, 255, 255, 0.05); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.1); transform-style: preserve-3d; }
                .card-flip { animation: flip 0.8s forwards; }
                @keyframes flip {
                    from { transform: rotateY(90deg); opacity: 0; }
                    to { transform: rotateY(0deg); opacity: 1; }
                }
            `}</style>
            
            <header className="mb-10">
                <h1 className="font-display text-6xl font-bold neon-text">Truth or Dare</h1>
            </header>

            <main>
                <div id="choice-screen" className={cn({ 'hidden': gameState !== 'choice' })}>
                    <p className="mb-8 text-lg text-gray-400">Pilih salah satu...</p>
                    <div className="flex flex-col sm:flex-row justify-center gap-6">
                        <button onClick={() => showResult('truth')} className="btn-choice btn-truth font-bold py-4 px-12 rounded-lg text-2xl">
                            <span>Truth</span>
                        </button>
                        <button onClick={() => showResult('dare')} className="btn-choice btn-dare font-bold py-4 px-12 rounded-lg text-2xl">
                            <span>Dare</span>
                        </button>
                    </div>
                </div>

                <div id="result-screen" className={cn({ 'hidden': gameState !== 'result' })}>
                    <div id="card" className={cn('min-h-[250px] p-8 rounded-2xl flex flex-col justify-center items-center', { 'card-flip': gameState === 'result' && !isFlipping })}>
                        <h2 className={cn('font-display text-3xl font-bold mb-4', {
                            'text-cyan-400 neon-text': resultType === 'TRUTH',
                            'text-pink-500 neon-text': resultType === 'DARE'
                        })}>
                            {resultType}
                        </h2>
                        <p className="text-xl leading-relaxed">{resultText}</p>
                    </div>
                    <button onClick={resetGame} className="mt-8 bg-gray-600 text-white font-bold py-3 px-8 rounded-full hover:bg-gray-700 transition">
                        Pemain Berikutnya
                    </button>
                </div>
            </main>
        </div>
    );
}

    